### ISSUE TITLE
右滑手势和地图冲突

### ISSUE THREAD

**Issue by mf168** [WAMaker/QQSlideMenu#1]
如果MainViewController是地图页面
会和地图右滑手势冲突 

有什么办法在地图页面的左边框范围处滑出LeftViewController ?

**Comment by WAMaker** [comment]
@wff- 我的理解是可以在地图的上面再覆盖一个view，用来处理滑动手势，Uber的左侧边栏应该就是这样做的

**Comment by mf168** [comment]
嗯嗯 谢谢了 试过可以 😁

**Comment by WAMaker** [comment]
@wff- 没事~

**Comment by wff-** [comment]
还有个问题 

集成这个侧边栏 导致 点击状态栏 tableView/scrollView 不能回到顶部
